[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
mantle = "${MANTLE_RPC_URL:-https://rpc.mantle.xyz}"
mantle_testnet = "${MANTLE_TESTNET_RPC_URL:-https://rpc.testnet.mantle.xyz}"
mantle_sepolia = "${MANTLE_SEPOLIA_RPC_URL:-https://rpc.sepolia.mantle.xyz}"

[etherscan]
mantle = { key = "${MANTLE_API_KEY}" }
mantle_testnet = { key = "${MANTLE_API_KEY}" }
mantle_sepolia = { key = "${MANTLE_API_KEY:-}" }
